"""Default Added

Revision ID: 5929b3311397
Revises: d575dfdd4e58
Create Date: 2025-01-12 19:34:43.465032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5929b3311397'
down_revision: Union[str, None] = 'd575dfdd4e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'userType',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'userType',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
