"""Initial setup or update

Revision ID: dae1364f43c0
Revises: 
Create Date: 2025-01-12 19:28:18.013644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae1364f43c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userType', sa.String(), nullable=True))
    # ### end Alembic commands ###

